service: faas-test
provider:
  name: aws
  runtime: nodejs10.x
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  imgresize:
    handler: handler.imgresize
    events:
      - http:
          path: /imgresize
          method: get
  id:
    handler: handler.id
    events:
      - http:
          path: id/{id}
          method: get



